name: windows

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby:
          - "3.0"
          - "2.7"
          - "2.6"
          - "2.5"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: |
          ridk enable
          pacman -Sy --noconfirm mingw-w64-x86_64-libmaxminddb
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: latest
          bundler-cache: true
      - name: Check Ruby version
        run: |
          ruby -v
      - name: Build
        run: |
          ridk enable
          bundle exec rake compile
      - name: Run test
        run: |
          ridk enable
          bundle exec rake test
